### PR TITLE
update metapackages to match variant definitions of REP-150

### PR DESCRIPTION
**Pull request by mikaelarguedas**
To be reviewed once https://github.com/ros-infrastructure/rep/pull/144/ is merged

### CODE REVIEW

**Review by dirk-thomas — APPROVED** [review]
I assume you created the new branch for `melodic-devel`. Please make it the default in the repo.

**Comment by mikaelarguedas** [comment]
> Please make it the default in the repo.

Will do :+1: 

General question, when do you usually change the default branch of your (code) repos?
- As soon as you branch out?
- As soon a you make a first release from that branch?
- when the new distro is announced?

**Comment by dirk-thomas** [comment]
> when do you usually change the default branch of your (code) repos?

As soon as I branch out. Basically I usually only merge PRs into the latest development branch to never "forward port".

**Comment by mikaelarguedas** [comment]
https://github.com/ros-infrastructure/rep/pull/144 is merged, merging this

**Pull request merged**
