### PR TITLE
Added genjs Javascript message gen to ros_core

### PR DESCRIPTION
**Pull request by IanTheEngineer**
This adds `genjs` as a core ROS package:
https://github.com/RethinkRobotics-opensource/genjs

This will be used with `rosjs` Javascript ROS client library:
https://github.com/RethinkRobotics-opensource/rosjs

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Can you please also create a pull request for the REP specifying the metapackages to reflect this.

**Comment by IanTheEngineer** [comment]
On it.

**Comment by IanTheEngineer** [comment]
For reference, here's the PR for REP 0142 https://github.com/ros-infrastructure/rep/pull/113

**Comment by jackieokay** [comment]
Closing this since the package was rennamed to gennodejs. @IanTheEngineer I've created a `kinetic-devel` branch which you can target the new branch to (this PR was targeted to jade).

**Pull request closed without merging**
